name: Update data.json

on:
  push:
    branches:
      - main  # Run workflow on push to main branch
  schedule:
    - cron: '0 * * * *'  # Run workflow every hour

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update data.json
        run: |
          # Simple script to update data.json
          # Replace this script with your logic to update your data
          echo '{"updated_at": "$(date)"}' > data.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m "Update data.json"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/neokusa/komen-blogspot.git HEAD:main
