name: Update data.json

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update data.json
      run: |
        # Your script to update data.json

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"
        git add data.json
        git commit -m "Update data.json"
        git push origin main
